http:
  routers:
    prometheus:
      rule: "Host(`prometheus.guide-it.ru`)"
      entrypoints:
        - websecure
      middlewares:
        - auth
      service: prometheus
      tls:
        certResolver: myresolver
    
    grafana:
      rule: "Host(`grafana.guide-it.ru`)"
      entrypoints:
        - websecure
      service: grafana
      tls:
        certResolver: myresolver
  
  services:
    prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"
    
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000" 